## Toolchain
javaVersion=21

## Plugin versions
springBootVersion=3.4.5
dependencyManagementVersion=1.1.7
kotlinVersion=2.1.20

## Dependency versions
springdocVersion=2.8.6
mockkVersion=1.13.16
springmockkVersion=4.0.2
testcontainersVersion=1.21.3
dockerJavaVersion=3.5.1
wiremockVersion=3.12.1
postgresqlVersion=42.7.4
