gateway:
  routes:
    - path-prefix: /api/auth
      target: http://auth-service:8080
      public: true
      strip-prefix: false
    - path-prefix: /api/users
      target: http://user-service:8080
      strip-prefix: false
    - path-prefix: /api/feed
      target: http://feed-service:8080
      strip-prefix: false
    - path-prefix: /api/interactions
      target: http://user-interactions-service:8080
      strip-prefix: false
    - path-prefix: /api/subscription
      target: http://subscription-service:8080
      strip-prefix: false
    - path-prefix: /webhook/yookassa
      target: http://subscription-service:8080
      public: true
      strip-prefix: false
    - path-prefix: /api/v1/sources
      target: http://config-service:8081
      strip-prefix: false
      required-roles:
        - SUBSCRIBER
    - path-prefix: /api/config
      target: http://content-aggregation-system:8086
      strip-prefix: false
      required-roles:
        - SUBSCRIBER
